# Generated by Django 3.2.7 on 2021-09-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=255, verbose_name='Name')),
                ('description', models.CharField(help_text='Description', max_length=255, verbose_name='Description')),
            ],
        ),
    ]
